### ISSUE TITLE
Where is the source code for the APK?

### ISSUE THREAD

**Issue by ubergeek77** [A2HI2H/Aosp_Dialer_With_Call_Recording#2]
Hi there!

I'd like to bake this into my own AOSP build and build this from source, so where can I find the source code for the APK? A googlesource.com or cs.android.com tag number for the original Dialer this was based on would also be very helpful, as it will allow me to diff the changes between the original source and the new source and turn it into a build-time patch.

Thanks!

**Comment by A2HI2H** [comment]
Its ported from aex custom rom , don't know about the source code

**Comment by ubergeek77** [comment]
Perfect, I didn't know this was from a ROM, but with that info I was able to find it here:

https://github.com/AospExtended/platform_packages_apps_Dialer/tree/9.x/java/com/android/dialer

It looks like their 10.x branch doesn't have it added though, but this should give me enough of an idea to add it myself.

Thanks!

**Comment by A2HI2H** [comment]
If you build this app from source , please theme it also , the apps looks
pale :)
